def print_one(str1):
    print(str1, end="")

def print_min(str1):
    return(str1 + ' ' + str1 + ' ' + str1 + ' ' + str1)

def do_twice(f, str1, str2, end_str):
    print(f(str1) + str2, end="")
    print(f(str1) + str2, end=end_str)

def do_four(f, str1, str2, end_str):
    print_one(str2)
    do_twice(f, str1, str2, end_str)
    print_one(str2)
    do_twice(f, str1, str2, end_str)
    print_one(str2)
    do_twice(f, str1, str2, end_str)
    print_one(str2)
    do_twice(f, str1, str2, end_str)

def grid_4():
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')

    print_one('+ ')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '\n')


def grid_8():
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '')
    do_twice(print_min, '-', ' + ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('| ')
    do_twice(print_min, ' ', ' | ', '')
    do_twice(print_min, ' ', ' | ', '\n')
    print_one('+ ')
    do_twice(print_min, '-', ' + ', '')
    do_twice(print_min, '-', ' + ', '\n')


grid_4()
grid_8()
